# permissions for end users to view rdbms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdbms-viewer-role
rules:
- apiGroups:
  - cloudfirst.cloudfirst.dev
  resources:
  - rdbms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudfirst.cloudfirst.dev
  resources:
  - rdbms/status
  verbs:
  - get
