namespace: release-namespace

bases:
- ../local-development/tilt

patchesJson6902:
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: MutatingWebhookConfiguration
    name: idp-operator-mutating-webhook-configuration
  path: ./cert-manager-ca-injection.yaml
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
    name: idp-operator-validating-webhook-configuration
  path: ./cert-manager-ca-injection.yaml