kind: Namespace
apiVersion: v1
metadata:
  name: mathianasj-backstage-runner
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
spec: {}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: mathianasj-backstage-runnerdeploy
  namespace: mathianasj-backstage-runner
spec:
  replicas: 1
  template:
    spec:
      dockerEnabled: false
      dockerdWithinRunnerContainer: false
      serviceAccountName: gh-runner
      resources: {}
      dockerdContainerResources: {}
      organization: mathianasj-backstage
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
        - name: GITHUB_OWNER
          value: mathianasj-backstage
        - name: RUNNER_HOME
          value: /home/runner
      containers:
        - name: runner
          resources: {}
          securityContext:
            capabilities:
              add:
                - CHOWN
                - SETUID
                - SETGID
                - FOWNER
                - DAC_OVERRIDE
                - CAP_SETGID
                - CAP_SETUID
            privileged: true
          volumeMounts:
            - name: github_token
              mountPath: "/_github"
              readOnly: true
      volumes:
        - name: github_token
          secret:
            secretName: controller-manager
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: gh-runner
  namespace: mathianasj-backstage-runner
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gh-runner-anyuid
  namespace: mathianasj-backstage-runner
subjects:
  - kind: ServiceAccount
    name: gh-runner
    namespace: mathianasj-backstage-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kaniko-scc-build
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gh-runner-kaniko-build
  namespace: mathianasj-backstage-runner
subjects:
  - kind: ServiceAccount
    name: gh-runner
    namespace: mathianasj-backstage-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kaniko-scc-build
