kind: Namespace
apiVersion: v1
metadata:
  name: mathianasj-backstage-runner
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
spec: {}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: mathianasj-backstage-runnerdeploy
  namespace: mathianasj-backstage-runner
spec:
  replicas: 1
  template:
    spec:
      organization: mathianasj-backstage